version: 2.1
jobs:
  release:
    machine:
      image: ubuntu-2004:202111-02
    environment:
      AWS_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
      AWS_ACCOUNT_ID: "883127560329"
      AWS_PROFILE: dev/vault
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Setup Environment
          command: |
            ./.circleci/setup-aws-config.sh
      - run:
          name: Build
          command: |
            docker build . -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/misc/apigentools:${CIRCLE_TAG}
      - run:
          name: Release
          command: |
            unset AWS_ACCESS_KEY_ID; unset AWS_SECRET_ACCESS_KEY;
            ./ops/docker-login.sh
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/misc/apigentools:${CIRCLE_TAG}

workflows:
  version: 2
  release:
    jobs:
      - release:
          context: circleci
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /.*/